CREATE TABLE IF NOT EXISTS users(
                                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                name VARCHAR(255) NOT NULL,
                                email VARCHAR(512) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS items (
                                     id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     name VARCHAR NOT NULL,
                                     description VARCHAR NOT NULL,
                                     is_available BOOLEAN NOT NULL,
                                     owner_id INTEGER NOT NULL,
                                     request_id INTEGER,
                        CONSTRAINT fk_items_owner_id FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS requests(
                                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    description  varchar NOT NULL,
                                    requestor_id  INTEGER NOT NULL,
                        CONSTRAINT fk_requests_requestor_id FOREIGN KEY (requestor_id) REFERENCES users (id) ON DELETE CASCADE

);

CREATE TABLE IF NOT EXISTS bookings(
                                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                start_date TIMESTAMP WITHOUT TIME ZONE,
                                end_date TIMESTAMP WITHOUT TIME ZONE,
                                item_id INTEGER,
                                booker_id INTEGER,
                                status VARCHAR,
                        CONSTRAINT fk_bookings_booker_id FOREIGN KEY (booker_id) REFERENCES users (id) ON DELETE CASCADE,
                        CONSTRAINT fk_bookings_item_id FOREIGN KEY (item_id) REFERENCES items (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS comments(
                                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    text VARCHAR,
                                    item_id INTEGER NOT NULL,
                                    author_id INTEGER NOT NULL,
                        CONSTRAINT fk_comments_item_id FOREIGN KEY (item_id) REFERENCES items (id) ON DELETE CASCADE,
                        CONSTRAINT fk_comments_author_id FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE CASCADE
);

