CREATE TABLE IF NOT EXISTS users(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email  varchar NOT NULL,
    name varchar NOT NULL
);

CREATE TABLE IF NOT EXISTS items (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         varchar NOT NULL,
    description  varchar NOT NULL,
    is_available BOOLEAN NOT NULL,
    owner_id     INTEGER NOT NULL,
    request_id   INTEGER,
        CONSTRAINT fk_items_owner_id FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE CASCADE,
        CONSTRAINT fk_items_request_id FOREIGN KEY (request_id) REFERENCES request (id) ON DELETE CASCADE
);
